# Generated by Django 6.0.6 on 2026-06-12 17:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('event_type', models.CharField(choices=[('GPS_DENIED', 'Gps Denied'), ('GPS_RECOVERED', 'Gps Recovered'), ('INHIBIT_SET', 'Inhibit Set'), ('INHIBIT_CLEARED', 'Inhibit Cleared'), ('OUTAGE_START', 'Outage Start'), ('OUTAGE_END', 'Outage End'), ('REBOOT_DETECTED', 'Reboot Detected'), ('DISH_UNREACHABLE', 'Dish Unreachable'), ('CONTROL_ACTION', 'Control Action'), ('WATCHDOG_MODE_CHANGED', 'Watchdog Mode Changed')], db_index=True, max_length=32)),
                ('source', models.CharField(choices=[('WATCHDOG', 'Watchdog'), ('USER', 'User'), ('SYSTEM', 'System')], max_length=16)),
                ('actor', models.CharField(max_length=150, null=True)),
                ('detail', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TelemetryReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('gps_valid', models.BooleanField(default=False)),
                ('gps_sats', models.IntegerField(default=0)),
                ('gps_inhibited', models.BooleanField(default=False)),
                ('pnt_filter_state', models.CharField(default='', max_length=64)),
                ('pop_ping_latency_ms', models.FloatField(null=True)),
                ('pop_ping_drop_rate', models.FloatField(default=0)),
                ('downlink_bps', models.FloatField(null=True)),
                ('uplink_bps', models.FloatField(null=True)),
                ('fraction_obstructed', models.FloatField(null=True)),
                ('attitude_uncertainty_deg', models.FloatField(null=True)),
                ('attitude_state', models.CharField(default='', max_length=64)),
                ('uptime_s', models.BigIntegerField(default=0)),
                ('software_version', models.CharField(default='', max_length=128)),
                ('country_code', models.CharField(default='', max_length=8)),
                ('disablement_code', models.CharField(default='', max_length=64)),
                ('outage_cause', models.CharField(max_length=64, null=True)),
                ('mobility_class', models.CharField(default='', max_length=64)),
                ('raw_json', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='WatchdogConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('LOG_ONLY', 'Log Only'), ('MONITOR', 'Monitor'), ('ENFORCE', 'Enforce')], default='LOG_ONLY', max_length=16)),
                ('poll_interval_s', models.IntegerField(default=10)),
                ('deny_debounce_s', models.IntegerField(default=90)),
                ('recover_debounce_s', models.IntegerField(default=120)),
                ('min_sats_for_good', models.IntegerField(default=5)),
                ('boot_warmup_s', models.IntegerField(default=300)),
                ('manual_override_until', models.DateTimeField(blank=True, null=True)),
                ('last_poll_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Watchdog Config',
                'verbose_name_plural': 'Watchdog Config',
            },
        ),
    ]
