# Generated by Django 6.0.6 on 2026-06-12 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dish', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telemetryreading',
            name='connectivity_ok',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='watchdogconfig',
            name='probe_hosts',
            field=models.TextField(default='8.8.8.8,1.1.1.1'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('GPS_DENIED', 'Gps Denied'), ('GPS_RECOVERED', 'Gps Recovered'), ('INHIBIT_SET', 'Inhibit Set'), ('INHIBIT_CLEARED', 'Inhibit Cleared'), ('OUTAGE_START', 'Outage Start'), ('OUTAGE_END', 'Outage End'), ('NET_OUTAGE_START', 'Net Outage Start'), ('NET_OUTAGE_END', 'Net Outage End'), ('REBOOT_DETECTED', 'Reboot Detected'), ('DISH_UNREACHABLE', 'Dish Unreachable'), ('CONTROL_ACTION', 'Control Action'), ('WATCHDOG_MODE_CHANGED', 'Watchdog Mode Changed')], db_index=True, max_length=32),
        ),
    ]
