# Generated by Django 6.0.6 on 2026-06-13 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dish', '0002_telemetryreading_connectivity_ok_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telemetryreading',
            name='is_snr_above_noise_floor',
            field=models.BooleanField(null=True),
        ),
    ]
