# Generated by Django 6.0.6 on 2026-06-13 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dish', '0003_telemetryreading_is_snr_above_noise_floor'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchdogconfig',
            name='last_retain_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
